POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "names": "Andres Felipe",
  "lastName": "Ramirez",
  "identification": "1234567890",
  "email": "andres@gmail.com",
  "password": "andres1234",
  "phoneNumber": "3102162732",
  "birthday": "2007-06-05"
}

###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "andres@gmail.com",
  "password": "andres1234"
}

###
GET http://localhost:8080/api/v1/seller/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0JVWUVSIl0sInN1YiI6IjEyMzQ1Njc4OTAiLCJpYXQiOjE3Njk5NzY4ODYsImV4cCI6MTc2OTk3NjkxNn0.ZXHPcDVSZEX0tH_H-gxAv3Q4qleNUzfBVPS9_gW7u834QREQxiFgCVvooQNgMxX-65c2otQRf1ft5eutNRmj7w
Content-Type: application/json

###
GET http://localhost:8080/api/v1/buyer/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0JVWUVSIl0sInN1YiI6IjEyMzQ1Njc4OTAiLCJpYXQiOjE3Njk5NzY4ODYsImV4cCI6MTc2OTk3NjkxNn0.ZXHPcDVSZEX0tH_H-gxAv3Q4qleNUzfBVPS9_gW7u834QREQxiFgCVvooQNgMxX-65c2otQRf1ft5eutNRmj7w
Content-Type: application/json